stream {
 map $ssl_preread_protocol $dangkou_protocol_upstream {
   "" 127.0.0.1:8080;
   default 127.0.0.1:443;
 }
 server {
   listen 80;
   ssl_preread on;
   proxy_pass $dangkou_protocol_upstream;
   proxy_connect_timeout 5s;
   proxy_timeout 180s;
 }
}
