"""Generate classic-browser and module catalogs from the one reviewed JSON resource."""
import json
from pathlib import Path
root=Path(__file__).resolve().parents[1]
catalog=json.loads((root/'frontend/src/customer-languages.json').read_text())
encoded=json.dumps(catalog,ensure_ascii=False,separators=(',',':'))
(root/'frontend/src/customer-catalog.js').write_text('// Generated by scripts/build_customer_languages.py\nexport default '+encoded+'\n')
(root/'static/customer-catalog.js').write_text('// Generated by scripts/build_customer_languages.py\nglobalThis.CustomerCatalog='+encoded+';\n')

(root/'static/customer-sources.js').write_text('// Generated by scripts/build_customer_languages.py\nglobalThis.CustomerSources='+json.dumps(json.loads((root/'frontend/src/customer-source-aliases.json').read_text()),ensure_ascii=False,separators=(',',':'))+';\n')

(root/'frontend/src/customer-sources.js').write_text('// Generated by scripts/build_customer_languages.py\nexport default '+json.dumps(json.loads((root/'frontend/src/customer-source-aliases.json').read_text()),ensure_ascii=False,separators=(',',':'))+'\n')
